### ISSUE TITLE
Question about nabu-instructions.md

### ISSUE THREAD

**Issue by DedBash** [dev-harsh1998/ota#1]
Hello @dev-harsh1998,
Would it not possibly sin instead of 
"boot
fastboot flash boot_a boot.img

fastboot flash boot_b boot.img"

simply fastboot flash boot_ab boot.img?

**Comment by dev-harsh1998** [comment]
yep you can, I have written those instructions in that way because a lot of people use old platform tools which might not directly support suffix _ab or --slot=all.
