### ISSUE TITLE
Nabu cant be turn off, it just reboots

### ISSUE THREAD

**Issue by deepblue2000** [dev-harsh1998/ota#12]
Nabu cant be turn off, it just reboots

you can only turn it off, if you boot to LOS Recovery and choose turn off

**Comment by foss-** [comment]
Not sure what you mean. I can both Power off and Restart a nabu device running this rom.

**Comment by dev-harsh1998** [comment]
@foss- @deepblue2000 Thanks for confirming the issue, I'll take a look into this before the next Release (Likely final A14)

**Comment by dev-harsh1998** [comment]
Works good on the new test build closing this
