### ISSUE TITLE
if bluetooth audio was connected, the internal speakers do not work unitl reboot

### ISSUE THREAD

**Issue by deepblue2000** [dev-harsh1998/ota#13]
if bluetooth audio was connected, the internal speakers do not work unitl reboot

**Comment by Ahmed-khalil3** [comment]
try this
https://bit.ly/4gwC82r

you may need to install the c compiler

**Comment by dev-harsh1998** [comment]
I tested the bluetooth audio and internal speakers they are both working fine for me.
