### ISSUE TITLE
restart disables dark mode

### ISSUE THREAD

**Issue by foss-** [dev-harsh1998/ota#15]
LineageOS 21-20240721-UNOFFICIAL-nabu

Restarting the tablet with dark mode enabled will show light mode once restart completes.

EDIT: persisting with LineageOS 20241003

**Comment by dev-harsh1998** [comment]
Tested with my current setup, can't be reproduced closing this

**Comment by foss-** [comment]
Hmm odd, this happens very frequently here. Turning the screen off seems sufficient in some cases. When re-opening I am welcomed by light mode.

**Comment by foss-** [comment]
This is still reproducible with 2024-10-21. Both  a restart or frequently even just turning off the display will switch to light mode.
