### ISSUE TITLE
Roblox mic not working.

### ISSUE THREAD

**Issue by cheemskek** [dev-harsh1998/ota#17]
LineageOS 21-20241003-UNOFFICIAL-nabu. Device (Xiaomi Pad 5 inbuilt mic) and earphone mic doesn't work in roblox.

Step to produce:

1. Clear log
2. Open Roblox, join a voice chat game.
3. Open the mic (not using earphone). Roblox doesn't detect input from mic.
4. Connect a earphone through 3.5MM to USB C dongle. Mic also not working.

Attachment:
[roblox.txt](https://github.com/user-attachments/files/17261607/roblox.txt)

**Comment by dev-harsh1998** [comment]
same as #16
