### ISSUE TITLE
(Request) Patch Kernel for Docker Support

### ISSUE THREAD

**Issue by Lobanokivan11** [dev-harsh1998/ota#18]
https://gist.github.com/FreddieOliveira/efe850df7ff3951cb62d74bd770dce27#41-kernel-patches
Hello Please Ads to the Lineageos Nabu Image Docker Support via Kernel. i'm serious. To install a docker Person Need to Patch Kernel.

**Comment by dev-harsh1998** [comment]
@Lobanokivan11 to me this looks rather like a very specific request we can take care of this when going forward with Lineage-22, Next/New releases of A14 based los-21 would only be security updates along with hw feature support, I'll add this to my list for los-22 once development for that is in pace.

Future plans for Los-22 based nabu builds include
* Face Unlock (AOSPA service, Probably)
* Support for changing wifi regions
* them docker patches that you mentioned (after looking into and understanding their need)
