### ISSUE TITLE
LineageOS-22 A15 sideload installation aborted

### ISSUE THREAD

**Issue by qin2hou** [dev-harsh1998/ota#21]
I am new user to flash lineage for the first time, just now I followed the flashing guide steps by steps,
the last sideload installation showed an error below:
recovery: Post build-tag release-keys does not match device build tag dev-keys
 
All the flashing files I download from the lastest Pre-release page.
[LineageOS-22 A15 QPR0 build for Xiaomi Pad 5 (nabu).](https://github.com/dev-harsh1998/ota/releases/tag/v1.4.5-Lineage-22-ALPHA-PAD5)

Pls help me with the problem.
Many thanks!

**Comment by qin2hou** [comment]
![IMG_3150](https://github.com/user-attachments/assets/ab9b96f5-c15a-4b98-a3dc-73bac14aff56)
![IMG_3151](https://github.com/user-attachments/assets/ac5d9c94-bc42-43ca-b20f-61e57b139e23)

**Comment by dev-harsh1998** [comment]
for now please use twrp to flash the build
