### ISSUE TITLE
Kernelsu giving error while flashing module

### ISSUE THREAD

**Issue by Vanilla-dot** [dev-harsh1998/ota#22]
Kernelsu giving error while flashing modules.

Error : Function not implemented (os error 38)
Flash Failed
[KernelSU_install_log_2024-11-11-04-16-02.log](https://github.com/user-attachments/files/17693332/KernelSU_install_log_2024-11-11-04-16-02.log)
![Screenshot_20241111-041439_Trebuchet](https://github.com/user-attachments/assets/db3691fc-ab8d-4af0-be62-1f12b61c9ef2)

Thanks for giving lineage-22.

**Comment by dev-harsh1998** [comment]
@Vanilla-dot This issue that you've made is unrelated to lineage builds please look out before opening new issues in future 

refer: https://github.com/tiann/KernelSU/issues/2186
