### ISSUE TITLE
(Bug) Please, fix systemui crashing on media plays.

### ISSUE THREAD

**Issue by Lobanokivan11** [dev-harsh1998/ota#23]
Hello! I have problem in lineageos 22. When i start listen a music or watch a movie systemui crashes and i always see lockscreen.
Please fix it!

**Comment by Lobanokivan11** [comment]
There Is Logcat log
[log.log](https://github.com/user-attachments/files/18040999/log.log)
I Use Lineageos 22.

**Comment by Lobanokivan11** [comment]
https://github.com/dev-harsh1998/ota/releases/tag/v1.4.6-Lineage-22-Beta-PAD5

**Comment by dev-harsh1998** [comment]
@Lobanokivan11 is this a fresh install of lineageos-22 (clean) ? I see a lot of permission denied failures and a few issues with tv launcher thingy, however media playback on my end works completely fine Netflix, youtube, music player etc. Please also list what magisk/kernel modules you are using.


Recommendation:
Try to do a fresh clean install.
If this issue reoccurs reopen this thread with the logs captured right through/after after the crash happened
