### ISSUE TITLE
zygisk next failed to load on KSU in 01-05 build

### ISSUE THREAD

**Issue by racalle** [dev-harsh1998/ota#3]
Hi, after latest ota something is not OK with Zygisk in KSU

Kernel problem maybe? Thx!

![Screenshot_20240503-182550_Trebuchet](https://github.com/dev-harsh1998/ota/assets/72765264/2696696d-44d7-490b-9409-97345e17ff68)
![Screenshot_20240503-182450_KernelSU](https://github.com/dev-harsh1998/ota/assets/72765264/7d2481bc-c222-4875-8bba-ebfe423f9411)

**Comment by dev-harsh1998** [comment]
Test on the newer build, I have updated kernelSU make sure the app is updated as well if the issue persists, Please reopen with `adb bugreport`

**Comment by racalle** [comment]
Problem persists with latest BETA and with today's zygisk-next module used in KSU.

Moreover, I had bootloop issue. I discovered how to stop it using safe_mode (up+down key during boot)

The bootloop maybe it's cause of zygisk-next or another rooted software I have, I don't know.

I attach the report and for now I am going two ROM's back and one zygisk-next version back so i reach an stable point. 

The ROM was working fine for me.

[bugreport-nabu_global-AP1A.240405.002.A1-2024-05-06-23-20-32.zip](https://github.com/dev-harsh1998/ota/files/15226733/bugreport-nabu_global-AP1A.240405.002.A1-2024-05-06-23-20-32.zip)
