### ISSUE TITLE
(Question) Does this work with the Xiaomi Pen? 

### ISSUE THREAD

**Issue by bammerlaan** [dev-harsh1998/ota#5]
I'm really not liking the Miui Android that the tablet comes with, I like LineageOS and this rom seems to still be updated quite regularly, so it seems a perfect fit. I do really need the Xiaomi pen to work with it, though. Any idea if that's possible with this rom?

**Comment by dev-harsh1998** [comment]
Xiaomi Pen is supported in the Rom build with the following code patch: https://github.com/dev-harsh1998/android_device_xiaomi_nabu-smol/commit/ccd7d9b369799c8ff0ff3e9f70f06f0c792d9cb3

**Comment by bammerlaan** [comment]
Nice! Thanks for replying and apologies for using the Issue tracker for this, I wasn't sure if there was a better place to ask. 

Changing OS on the Mi Pad 5 will be my project for today, then!
