### ISSUE TITLE
5Ghz Wifi not working (Germany)

### ISSUE THREAD

**Issue by Simsala91** [dev-harsh1998/ota#6]
I'm having trouble with connecting to my home 5Ghz network. This was not an issue before I switched from stock ROM. It might have something to do with wifi country codes, but I'm not sure. I have a Xiaomi Pad 5, EU Version (256GB) and I am living in Germany.

Is there any way this can be fixed?

**Comment by dev-harsh1998** [comment]
Hi @Simsala91 can you please drop bugreport `adb bugreport` after you try to connect with affected access point, Also can you tell me more about what wifi channel and width you are using (20mhz / 40mhz) along with the security type of the endpoint you're trying to associate with

**Comment by Simsala91** [comment]
Hi @dev-harsh1998, thanks for the quick response!

So a few additional informations:

Usually, I have a single SSID for both 2.4/5 Ghz. But I realized that data rates are low and that some downloads sometimes fail. Then I checked wifi settings on the device and saw that it is only connected to the 2.4Ghz Wifi. I separated SSIDs, but the 5Ghz Wifi is not visible at all, so I have no option to even try to connect to it (works fine from my phone). I changed Wifi standard from 6 to 5 to 4, but the wifi is not visible with any setting.

Current channel is 112, width setting in router is (20/40/80), my phone seems to use 80.

Security is WPA2-Personal / AES.

[bugreport-lineage_nabu-AP2A.240605.024-2024-07-10-11-18-23.zip](https://github.com/user-attachments/files/16158737/bugreport-lineage_nabu-AP2A.240605.024-2024-07-10-11-18-23.zip)

Appended bugreport where I connected to the dual 2.4/5Ghz network but only got 2.4 Ghz connection. Also there were some failed downloads during that time.

**Comment by dev-harsh1998** [comment]
Hi @Simsala91 please try out the latest build and let me know if you see differences if the issue persists please open the ticket again with new logs

**Comment by Simsala91** [comment]
@dev-harsh1998 Sadly, it's still not working flawlessly. 
I updated it and it still did not connect to my 5Ghz Wifi. But I realized that I saw some networks that ended with "-5Ghz". So I downloaded the Wifi-Analyzer app on both my phone and the tablet, and realized that the tablet did not find any 5Ghz networks with channels 100+. I was able to connect to my 5ghz hotspot from my phone (Channel 36).

I will change the channel of my router to 36 in the evening and do some more testing then.

**Comment by dev-harsh1998** [comment]
https://www.qualcomm.com/products/technology/wi-fi/fastconnect/fastconnect-6200
Apparently anything over 80mhz is a pushover for the chip inside the device.

**Comment by Simsala91** [comment]
The network isn't above 80 Mhz though... The tablet just isn't capable to connect to any channels that are between 100 and ~140.

I switched my wifi settings to channel 40, and now it is connecting to the 5Ghz network and downloads are no longer failing. 

Before that, here are comparision pictures from my phone and my tablet:

![tablet -  no networks with channel 100+](https://github.com/user-attachments/assets/4eb243f6-4e20-44e9-a0d8-0be9a04cc206)

![phone - networks with channel 100 and 112 showings (80mhz, same as some other on the tablet)](https://github.com/user-attachments/assets/51f54322-395d-45fe-a5b4-f46b6526d4dd)

Me switching my Wifi channel will only fix this for my home network though, might still run into bugs when trying to connect at a friends house.

**Comment by foss-** [comment]
Running lineage-21.0-20240721-UNOFFICIAL-nabu, also in germany, can confirm this finding: with the router set to auto-channel whenever the 5-Ghz wifi lands on a channel >= 100 the wifi is gone and not detected.

And yes, the channel can manually be set to a lower channel, but that does not resolve the issue for other wifi outside of home.

Can the issue be re-opened?

**Comment by foss-** [comment]
polite ping @dev-harsh1998

**Comment by foss-** [comment]
Confirming - this is fascinating. My latest understanding was that this is a limitation on hardware side. Happy to be wrong I guess 🥳

**Comment by dev-harsh1998** [comment]
Glad to hear about it :) 
Seems like we are striking off points very well from this comment of mine 
https://github.com/dev-harsh1998/ota/issues/18#issuecomment-2427270784
